import Head from 'next/head'
import Link from 'next/link'


export default function About() {
  return (
    <>
      <Head>
        <title>De forenede kålavlere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='icon' href='/cabbage.png'/>
      </Head>
      
      <div className='w-full mt-[8rem] mb-[6rem] h-auto flex flex-col justify-center items-center md:flex md:items-center md:justify-between'>
      <h1 className='text-[#41a950] text-6xl font-bold text-center'>De forenede kålavlere</h1>
      <p className='text-gray-400 text-lg pt-5'>Et enestående samarbejde mellem <span className='text-[#41a950]'>Svinningegaard</span>,<span className='text-[#41a950]'> Månsson</span> og <span className='text-[#41a950]'>Kroghs Grønt</span> </p>
      <div className='flex justify-items-start items-center mx-40 gap-10'>
      <div className='flex gap-32 pt-10'>
        <img src='Billede1.png' className='w-[25%] h-[25%] pt-5 px-5 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 cursor-pointer block ml-auto mr-auto'/>
        <img src='mansson.png' className='w-[30%] h-[30%] px-5 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 cursor-pointer block ml-auto mr-auto'/>
        <img src='cropped-logo2.png' className='w-[25%] h-[25%] px-5 pl-10 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 cursor-pointer block ml-auto mr-auto'/>
      </div>
     </div> 
    </div>
    <div className=' text-center pb-16'>
    <div className=' h-[100%] w-[45%] inline-block'>
      <h2 className='font-bold text-[#41a950] text-3xl pb-2'>Fra jord til bord</h2>
      <p className='md:text-base text-gray-400 text-center md-text-center sm:text-left sm:text-sm'>Hos de forenede kålavlere produceres der udelukkende friske økologiske kål, som er    med til at skåne miljøet og er godt for dit helbred. Hos de forenede kålavlere, forsøger vi hele tiden med nye kål og sorter, for at forbedre oplevelsen, kvaliteten og dyrkningen af kål</p>
    </div>
    <div className='h-[100%] w-[45%] inline-block'>
      <h2 className='font-bold text-[#41a950] text-3xl pb-2'>Spark dit kålforbrug igang</h2>
      <p className='md:text-base text-center text-gray-400 md-text-center sm:text-left sm:text-sm'>De forenede kålavlere er din oplagte mulighed, for at sparke dit kålforbrug igang. Følg aktivt hjemmesiden eller vores sociale medier, for opdateringer omkring de nyeste og lækreste retter!</p>
    </div>
    </div>
    

    </>
  )
}
