import Head from 'next/head'
import Link from 'next/link'


export default function About() {
  return (
    <>
      <Head>
        <title>Svinningegaard - Om os</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='icon' href='/cabbage.jpeg'/>
      </Head>
    <div className='bg-gray-50 h-1/2 w-full flex md:flex-row flex-col justify-around items-start p-20'>
    <div className='p-5'>
      <ul>
        <p className='text-gray-800 font-bold text-2xl pb-4'>Kål fra friland</p>
        <img src='Kål.jpeg' className='w-3/5 h-3/5'/>
        <li>Dansk kål fra friland, Svinningegaard</li>
      </ul>
    </div>
    <div className='p-5'>
      <ul>
        <p className='text-gray-800 font-bold text-lg'>Genveje til opskrifter</p>
        <div className='text-gray-500 text-md pb-2 font-semibold'>
          <Link href='/food'><li className='text-blue-600 cursor-pointer pb-7 hover:text-[#41a950]'>Se udvalget af opskrifter på nem mad</li></Link>
          {/* TODO: Husk at lave det om til eks. "Lækker pizza med kål" i stedet for "Lækker mad med Blomkål"*/}
          <a target='_blank' rel='noreferrer' title='Åben Svinningegaard.com' href='http://www.svinningegaard.dk/nem-mad/nem-mad-med-blomkaal/'><li className='text-blue-600 cursor-pointer hover:text-[#41a950]'>Lækker mad med Blomkål</li></a>
          <a target='_blank' rel='noreferrer' title='Åben Svinningegaard.com' href='http://www.svinningegaard.dk/nem-mad/nem-mad-med-blomkaal/'><li className='text-blue-600 cursor-pointer hover:text-[#41a950]'>Lækker mad med Kinakål</li></a>
          <a target='_blank' rel='noreferrer' title='Åben Svinningegaard.com' href='http://www.svinningegaard.dk/nem-mad/nem-mad-med-blomkaal/'><li className='text-blue-600 cursor-pointer hover:text-[#41a950]'>Lækker mad med Rød Kinakål</li></a>
        </div>
        <a target="_blank" rel="noreferrer" title="Åben Google Maps">
          <li className='text-blue-600 text-md pt-4 font-semibold cursor-pointer '>Vis på Google Maps</li>
        </a>
      
      </ul>
    </div>
  
  </div>
  

    </>
  )
}
