import Head from 'next/head'
import styled from 'styled-components';
import Content from '../components/Content';

const Hero = styled.div`
  height: 90vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 10rem;
  font-weight: 900;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>De forenede kålavlere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cabbage.png" />
      </Head>


      <div className='bg-plakat_bg bg-center bg-cover bg-scroll bg-blend-multiply bg-no-repeat w-[100%] py-10'>
      <h1 className='text-[#4021ba] text-center text-7xl pt-40 p-52 font-bold'>HER KOMMER KÅL </h1>
      </div>
      <Content />
    </>
  )
}
